# Generated by Django 5.2.16 on 2026-09-14 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("root_hash", models.CharField(max_length=64)),
                ("heads", models.JSONField(default=list)),
                (
                    "log",
                    models.CharField(
                        default="local",
                        help_text="local | opentimestamps",
                        max_length=24,
                    ),
                ),
                ("proof", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Ask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("write", "Writing"), ("review", "Reviewing")],
                        default="write",
                        max_length=8,
                    ),
                ),
                (
                    "unit_id",
                    models.CharField(
                        blank=True, help_text="Blank = the whole paper.", max_length=64
                    ),
                ),
                ("device_code", models.CharField(max_length=32)),
                ("yukti", models.CharField(blank=True, max_length=32)),
                ("count", models.PositiveSmallIntegerField(default=3)),
                ("instruction", models.TextField(blank=True)),
                ("constraint", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("failed", "Failed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "check_text",
                    models.TextField(
                        blank=True,
                        help_text="The AI's account of how to test this candidate.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=40)),
                ("reason_note", models.TextField(blank=True)),
                ("placed_unit", models.CharField(blank=True, max_length=64)),
                ("examined_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ask",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="lekhana.ask",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "examined_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("author", "Author"), ("reviewer", "Reviewer")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lekhana_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["role", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="lekhana_projects",
                        through="lekhana.Membership",
                        through_fields=("project", "user"),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="membership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="lekhana.project",
            ),
        ),
        migrations.AddField(
            model_name="ask",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asks",
                to="lekhana.project",
            ),
        ),
        migrations.CreateModel(
            name="ReviewPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_id",
                    models.CharField(
                        blank=True, help_text="Blank = the whole paper.", max_length=64
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("question", "Question"),
                            ("objection", "Objection"),
                            ("inconsistency", "Inconsistency"),
                            ("suggestion", "Suggestion"),
                            ("strength", "Strength"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField()),
                ("response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_points",
                        to="lekhana.project",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        help_text="human:<username> or ai:<model>", max_length=96
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("svatantra", "Independent (svatantra)"),
                            ("prayojaka", "Directing (prayojaka)"),
                            ("prayojya", "Directed (prayojya)"),
                            ("sakshin", "Examiner (sākṣin)"),
                            ("parikshaka", "Reviewer (parīkṣaka)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("frame", "Frame the work"),
                            ("instruct", "Instruct the AI"),
                            ("draft", "Draft (changes what the text asserts)"),
                            ("object", "Object (pūrvapakṣa)"),
                            ("rebut", "Reply (uttarapakṣa)"),
                            ("respond", "Respond to a review point"),
                            ("rephrase", "Rephrase (form only)"),
                            ("affirm", "Accept after examining"),
                            ("flag_defect", "Reject, naming a defect"),
                            ("reject", "Reject on other grounds"),
                            ("reserve", "Reserve a slot"),
                            ("review_ask", "Ask the paper while reviewing"),
                            ("explain", "Answer a reviewer's ask"),
                            ("review_point", "Raise a review point"),
                            ("grant", "Grant access"),
                            ("unexamined_assent", "Accept without examining"),
                        ],
                        max_length=24,
                    ),
                ),
                ("yukti", models.CharField(blank=True, max_length=32)),
                ("unit_id", models.CharField(blank=True, max_length=64)),
                ("meaning_bearing", models.BooleanField(blank=True, null=True)),
                ("defect", models.CharField(blank=True, max_length=40)),
                ("note", models.TextField(blank=True)),
                (
                    "commit_sha",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The signed-in person this act was performed by or on behalf of.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ask",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acts",
                        to="lekhana.ask",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acts",
                        to="lekhana.candidate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acts",
                        to="lekhana.project",
                    ),
                ),
                (
                    "review_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acts",
                        to="lekhana.reviewpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                fields=("ask", "index"), name="lekhana_candidate_unique_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="lekhana_membership_unique"
            ),
        ),
    ]
