# Generated by Django 5.2.16 on 2026-09-26 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekhana", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="kind",
            field=models.CharField(
                choices=[
                    ("frame", "Frame the work"),
                    ("instruct", "Instruct the AI"),
                    ("say", "Say something in discussion"),
                    ("answer", "Answer in discussion"),
                    ("record_idea", "Record an idea"),
                    ("attribute", "Confirm or correct an attribution"),
                    ("set_stance", "Set the AI's role"),
                    ("method_start", "Start a writing method"),
                    ("method_step", "Complete a method step"),
                    ("compile", "Compile the PDF"),
                    ("export", "Export the paper"),
                    ("draft", "Draft (changes what the text asserts)"),
                    ("object", "Object (pūrvapakṣa)"),
                    ("rebut", "Reply (uttarapakṣa)"),
                    ("respond", "Respond to a review point"),
                    ("rephrase", "Rephrase (form only)"),
                    ("affirm", "Accept after examining"),
                    ("flag_defect", "Reject, naming a defect"),
                    ("reject", "Reject on other grounds"),
                    ("reserve", "Reserve a slot"),
                    ("review_ask", "Ask the paper while reviewing"),
                    ("explain", "Answer a reviewer's ask"),
                    ("review_point", "Raise a review point"),
                    ("grant", "Grant access"),
                    ("unexamined_assent", "Accept without examining"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                (
                    "stance",
                    models.CharField(
                        choices=[
                            ("interlocutor", "Interlocutor"),
                            ("socratic", "Socratic"),
                            ("examiner", "Examiner"),
                            ("devils_advocate", "Devil's advocate"),
                            ("scribe", "Scribe"),
                            ("partner", "Partner"),
                        ],
                        default="interlocutor",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="lekhana.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="act",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acts",
                to="lekhana.conversation",
            ),
        ),
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("framing", "Framing"),
                            ("term", "Term"),
                            ("question", "Question"),
                            ("objection", "Objection"),
                            ("method", "Method"),
                            ("example", "Example"),
                        ],
                        default="idea",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        help_text="human:<username> or ai:<model>", max_length=96
                    ),
                ),
                (
                    "units",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Unit ids that realise this idea.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("used", "In the paper"),
                            ("dropped", "Dropped"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "corrected",
                    models.BooleanField(
                        default=False,
                        help_text="True when a person changed the claimed origin.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to="lekhana.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="act",
            name="idea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acts",
                to="lekhana.idea",
            ),
        ),
        migrations.CreateModel(
            name="MethodRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="method_runs",
                        to="lekhana.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                (
                    "speaker",
                    models.CharField(
                        choices=[("human", "Writer"), ("ai", "AI")], max_length=8
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "tool_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tools the AI used on this turn, with their inputs.",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=64)),
                ("stance", models.CharField(blank=True, max_length=24)),
                (
                    "flagged",
                    models.CharField(
                        blank=True,
                        help_text="Set when the reply broke the stance's restrictions.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="lekhana.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.AddField(
            model_name="idea",
            name="origin_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ideas",
                to="lekhana.turn",
            ),
        ),
        migrations.CreateModel(
            name="MethodStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=300)),
                ("unit_id", models.CharField(blank=True, max_length=64)),
                ("done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="lekhana.methodrun",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "index"), name="lekhana_methodstep_unique_index"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                fields=("conversation", "index"), name="lekhana_turn_unique_index"
            ),
        ),
    ]
