# Generated by Django 5.2.16 on 2026-09-26 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekhana", "0002_alter_act_kind_conversation_act_conversation_idea_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="track_composition",
            field=models.BooleanField(
                default=True,
                help_text="Record how text arrives in the editor: characters typed, and each paste's length and hash (never its text). Authors can turn it off; the change is an act.",
            ),
        ),
        migrations.AlterField(
            model_name="act",
            name="kind",
            field=models.CharField(
                choices=[
                    ("frame", "Frame the work"),
                    ("instruct", "Instruct the AI"),
                    ("say", "Say something in discussion"),
                    ("answer", "Answer in discussion"),
                    ("record_idea", "Record an idea"),
                    ("attribute", "Confirm or correct an attribution"),
                    ("set_stance", "Set the AI's role"),
                    ("set_tracking", "Change composition tracking"),
                    ("method_start", "Start a writing method"),
                    ("method_step", "Complete a method step"),
                    ("compile", "Compile the PDF"),
                    ("export", "Export the paper"),
                    ("draft", "Draft (changes what the text asserts)"),
                    ("object", "Object (pūrvapakṣa)"),
                    ("rebut", "Reply (uttarapakṣa)"),
                    ("respond", "Respond to a review point"),
                    ("rephrase", "Rephrase (form only)"),
                    ("affirm", "Accept after examining"),
                    ("flag_defect", "Reject, naming a defect"),
                    ("reject", "Reject on other grounds"),
                    ("reserve", "Reserve a slot"),
                    ("review_ask", "Ask the paper while reviewing"),
                    ("explain", "Answer a reviewer's ask"),
                    ("review_point", "Raise a review point"),
                    ("grant", "Grant access"),
                    ("unexamined_assent", "Accept without examining"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="CompositionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("typing", "Typed"), ("paste", "Pasted")], max_length=8
                    ),
                ),
                ("unit_id", models.CharField(blank=True, max_length=64)),
                ("chars", models.PositiveIntegerField(default=0)),
                ("text_hash", models.CharField(blank=True, max_length=64)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ai_candidate", "From the AI's candidates"),
                            ("own_paper", "From elsewhere in this paper"),
                            ("outside", "From outside the portal"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "commit_sha",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pastes",
                        to="lekhana.candidate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composition",
                        to="lekhana.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("chars", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="lekhana.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
